<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Product extends Model implements Hasmedia
{
    use HasMediaTrait;

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($product) {
            $product->slug = str_slug($product->title);
        });
    }

    public function getTitleAttribute($value): string
    {
        return ucfirst($value);
    }

    public function category(): HasOne
    {
        return $this->hasOne(Category::class);
    }


}
